models/Events.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "events".
 *
 * @property int $event_id
 * @property int|null $room_id
 * @property string|null $event_name
 * @property string|null $start_date
 * @property string|null $end_date
 * @property int|null $participants
 * @property string|null $snacks
 * @property string|null $projector
 * @property string|null $conference
 * @property string|null $recorder
 * @property string|null $request_by
 * @property string|null $request_date
 */
class Events extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'events';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['room_id', 'participants'], 'integer'],
            [['start_date', 'end_date', 'request_date'], 'safe'],
            [['snacks', 'projector', 'conference', 'recorder','lunch'], 'string'],
            [['event_name', 'request_by','eventColor'], 'string', 'max' => 255],
            [['start_date', 'end_date','event_name', 'request_by','room_id', 'participants',], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'event_id' => 'ลำดับที่',
            'room_id' => 'ห้อง',
            'event_name' => 'เรื่อง',
            'start_date' => 'วันเวลาที่เริ่มการประชุม',
            'end_date' => 'วันเวลาสิ้นสุดการประชุม',
            'participants' => 'จำนวนผู้เข้าร่วม',
            'snacks' => 'อาหารว่าง',
            'lunch' => 'อาหารเที่ยง',
            'projector' => 'โปรเจ็คเตอร์',
            'conference' => 'ประชุมทางไกล',
            'recorder' => 'เครื่องอัดเสียง',
            'request_by' => 'ผู้ขอใช้ห้องประชุม',
            'request_date' => 'วันที่ขอใช้',
            'eventColor' => 'สี',
        ];
    }

    public function getRooms(){
        return $this->hasOne(Rooms::className(), ['room_id' => 'room_id']);
    }
}

controllers/EventsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Events;
use app\models\EventsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EventsController implements the CRUD actions for Events model.
 */
class EventsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Events models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EventsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Events model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Events model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Events();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->event_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Events model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->event_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Events model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Events model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Events the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Events::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/events/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datetime\DateTimePicker;
use yii\helpers\ArrayHelper;

use app\models\Rooms;

$rooms = ArrayHelper::map(Rooms::find()->all(),'room_id','room_name');
$color = [
    'Red'  => '<div class="panel" style="background:red;color:white;width:50px"> <br> </div>',
    'Blue' => '<div class="panel" style="background:blue;color:white;width:50px"> <br> </div>' ,
    'Green' => '<div class="panel" style="background:green;color:white;width:50px"> <br> </div>' , 
    'Gold' => '<div class="panel" style="background:gold;color:white;width:50px"> <br> </div>', 
    'Black' => '<div class="panel" style="background:black;color:white;width:50px"> <br> </div>', 
    'Orange' => '<div class="panel" style="background:orange;color:white;width:50px"> <br> </div>', 
    'Purple' => '<div class="panel" style="background:purple;color:white;width:50px"> <br> </div>', 
    'Magenta' => '<div class="panel" style="background:magenta;color:white;width:50px"> <br> </div>' , 
    'Brown' => '<div class="panel" style="background:brown;color:white;width:50px"> <br> </div>' ];
$color = [
    'Red' => 'สีแดง',
    'Blue' => 'สีน้ำเงิน',
    'Green' => 'สีเขียว',
    'Gold' => 'สีเหลือง',
    'Orange' => 'สีส้ม',
    'Brown' => 'สีน้ำตาล',
    'Purple' => 'สีม่วง',
    'Magenta' => 'สีชมพู',
    'Black' => 'สีดำ',
];
    /* @var $this yii\web\View */
/* @var $model app\models\Events */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="events-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <?= $form->field($model, 'room_id')->radioList($rooms) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <?= $form->field($model, 'event_name')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-sm-12">
            <?php 
                echo '<label class="control-label">วัน เวลาเริ่มประชุม</label>';
                echo DateTimePicker::widget([
                    'model' => $model,
                    'attribute' => 'start_date',
	                'value' => date('Y-m-d H:i:s'),
	                'pluginOptions' => [
		                'autoclose' => true,
		                'format' => 'yyyy-mm-dd hh:ii:ss'
	                ]
                ]); 
            ?>
        </div>
        <div class="col-md-4 col-sm-12">
            <?php 
                echo '<label class="control-label">วัน เวลาสิ้นสุดประชุม</label>';
                echo DateTimePicker::widget([
                    'model' => $model,
                    'attribute' => 'end_date',
	                'value' => date('Y-m-d H:i:s'),
	                'pluginOptions' => [
		                'autoclose' => true,
		                'format' => 'yyyy-mm-dd hh:ii:ss'
	                ]
                ]); 
            ?>
        </div>
        <div class="col-md-4 col-sm-12">
            <?= $form->field($model, 'participants')->textInput() ?>
        </div>
    </div>
    <?= $form->field($model, 'snacks')->checkbox() ?>
    <?= $form->field($model, 'lunch')->checkbox() ?>
    <?= $form->field($model, 'projector')->checkbox() ?>
    <?= $form->field($model, 'conference')->checkbox() ?>
    <?= $form->field($model, 'recorder')->checkbox() ?>
    <?= $form->field($model, 'request_by')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'eventColor')->radioList($color) ?>

    <?php /*= $form->field($model, 'eventColor')->radioList($color,['item' => function($index, $label, $name, $value) {
        $return = '<label class="modal-radio">';
        $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" tabindex="1">';
        //$return .= '<i></i>';
        $return .=  ucwords($label) ;
        $return .= '</label>';
        return $return;}])->label(false); */?>
    <div class="form-group">
        <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/events/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\EventsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="events-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'event_id') ?>

    <?= $form->field($model, 'room_id') ?>

    <?= $form->field($model, 'event_name') ?>

    <?= $form->field($model, 'start_date') ?>

    <?= $form->field($model, 'end_date') ?>

    <?= $form->field($model, 'participants') ?>

    <?php // echo $form->field($model, 'snacks') ?>

    <?php // echo $form->field($model, 'projector') ?>

    <?php // echo $form->field($model, 'conference') ?>

    <?php // echo $form->field($model, 'recorder') ?>

    <?php // echo $form->field($model, 'request_by') ?>

    <?php // echo $form->field($model, 'request_date') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/events/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = 'Create Events';
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\icons\Icon;
Yii::$app->formatter->locale = 'th_TH';

/* @var $this yii\web\View */
/* @var $searchModel app\models\EventsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Events';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('เพิ่มการประชุม', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'event_id',
            //'rooms.room_name',
            'event_name',
            'start_date',
            'end_date',
            'participants',
            //'snacks',
            //'projector',
            //'conference',
            //'recorder',
            // แสดงข้อมูลออกเป็น icon
            [ 
                'attribute' => 'snacks',
                'format'=>'html',
                'value'=>function($model, $key, $index, $column){
                  return $model->snacks==1 ? "<span style=\"color:green;\"><i class=\"glyphicon glyphicon-ok\"></i></span>" : "<span style=\"color:red;\"><i class=\"glyphicon glyphicon-remove\"></i></span>";
                }
            ],
            [ 
                'attribute' => 'lunch',
                'format'=>'html',
                'value'=>function($model, $key, $index, $column){
                  return $model->lunch==1 ? "<span style=\"color:green;\"><i class=\"glyphicon glyphicon-ok\"></i></span>" : "<span style=\"color:red;\"><i class=\"glyphicon glyphicon-remove\"></i></span>";
                }
            ],
            [ 
                'attribute' => 'projector',
                'format'=>'html',
                'value'=>function($model, $key, $index, $column){
                  return $model->projector==1 ? "<span style=\"color:green;\"><i class=\"glyphicon glyphicon-ok\"></i></span>" : "<span style=\"color:red;\"><i class=\"glyphicon glyphicon-remove\"></i></span>";
                }
            ],
            [ 
                'attribute' => 'conference',
                'format'=>'html',
                'value'=>function($model, $key, $index, $column){
                  return $model->conference==1 ? "<span style=\"color:green;\"><i class=\"glyphicon glyphicon-ok\"></i></span>" : "<span style=\"color:red;\"><i class=\"glyphicon glyphicon-remove\"></i></span>";
                }
            ],
            [ 
                'attribute' => 'recorder',
                'format'=>'html',
                'value'=>function($model, $key, $index, $column){
                  return $model->recorder==1 ? "<span style=\"color:green;\"><i class=\"glyphicon glyphicon-ok\"></i></span>" : "<span style=\"color:red;\"><i class=\"glyphicon glyphicon-remove\"></i></span>";
                }
            ],
            'request_by',
            //'request_date',
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{view}',
                'buttons'=>[
                    'view' => function($url,$model,$key){
                      return Html::a('รายละเอียด',['events/view','id'=>$model->event_id],['class' => 'btn btn-info']);
                    }
                ]
             ],
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{update}',
                'buttons'=>[
                    'update' => function($url,$model,$key){
                      return Html::a('แก้ไข',['events/update','id'=>$model->event_id],['class' => 'btn btn-success']);
                    }
                ]
             ],
             [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-primary'],
                'template'=>'{delete}',
                'buttons'=>[
                    'delete' => function($url,$model,$key){
                      return Html::a('ลบ',['events/delete','id'=>$model->event_id],['class' => 'btn btn-danger']);
                    }
                ]
             ],
        ],
    ]); ?>


</div>

views/events/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = 'Update Events: ' . $model->event_id;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->event_id, 'url' => ['view', 'id' => $model->event_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="events-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = $model->event_id;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="events-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (!Yii::$app->user->isGuest) { ?>
    <p>
        <?= Html::a('Update', ['update', 'id' => $model->event_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->event_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php } ?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'event_id',
            'room_id',
            'event_name',
            'start_date',
            'end_date',
            'participants',
            'snacks',
            'projector',
            'conference',
            'recorder',
            'request_by',
            'request_date',
        ],
    ]) ?>

</div>